USE university_project_sql_schema;

INSERT INTO students (students_first_name,students_last_name,students_email)
VALUES
  ("Jelani","Bradshaw","sit.amet@outlook.com"),
  ("Melvin","Hardin","ultrices@outlook.net"),
  ("Edward","Mclaughlin","nec.urna@protonmail.couk"),
  ("Sylvester","Lott","accumsan.sed@hotmail.net"),
  ("Ronan","Scott","ornare.elit@aol.com"),
  ("Curran","Clark","cubilia.curae.phasellus@hotmail.edu"),
  ("Peter","Strong","magna.sed.dui@outlook.org"),
  ("Fulton","Clements","a.aliquet.vel@hotmail.com"),
  ("Knox","Luna","non.leo@outlook.ca"),
  ("Abel","Brooks","sollicitudin@outlook.org"),
  ("Otto","Hendrix","consequat@yahoo.net"),
  ("Arthur","Doyle","sapien.gravida.non@protonmail.net"),
  ("Harlan","Mayo","tristique.ac@aol.net"),
  ("Logan","Christensen","sapien.imperdiet@yahoo.org"),
  ("Christopher","Fitzgerald","primis.in.faucibus@yahoo.ca"),
  ("Orlando","Mcleod","enim.nisl@icloud.edu"),
  ("Stone","Romero","aliquet.molestie.tellus@yahoo.ca"),
  ("Nissim","Cabrera","fringilla.est.mauris@google.com"),
  ("Akeem","Dunn","natoque@hotmail.couk"),
  ("Andrew","Chavez","pede.cum@protonmail.org"),
  ("Macaulay","Todd","lacinia@outlook.net"),
  ("Russell","Meyers","primis.in@hotmail.com"),
  ("Jerry","Hewitt","vel@aol.com"),
  ("Gannon","Ball","eu.tellus@hotmail.couk"),
  ("Nathan","Simon","a@google.net"),
  ("Lamar","Benson","volutpat.nulla@google.ca"),
  ("Caldwell","Dickson","enim.mauris@aol.net"),
  ("Adam","Frost","quis.pede.praesent@yahoo.couk"),
  ("Uriel","Phillips","in@icloud.com"),
  ("Thane","Roach","varius.ultrices.mauris@outlook.couk"),
  ("Ivor","George","ac.urna@hotmail.net"),
  ("George","Lyons","condimentum.donec@protonmail.couk"),
  ("Christopher","Lucas","nunc.ut@aol.couk"),
  ("Jin","Figueroa","dictum.magna.ut@outlook.com"),
  ("Vernon","Gamble","sem.ut@protonmail.com"),
  ("Zeph","Roy","justo@protonmail.org"),
  ("James","Brady","integer@icloud.org"),
  ("Ryan","Wong","sit.amet.risus@hotmail.couk"),
  ("Channing","Matthews","aliquam.gravida.mauris@aol.org"),
  ("Branden","Greene","dapibus.quam@google.com"),
  ("Preston","Randolph","odio.sagittis@google.ca"),
  ("Aladdin","Barlow","non.enim@google.ca"),
  ("Tanner","Sawyer","nullam@aol.ca"),
  ("Francis","Hopper","nullam@google.edu"),
  ("August","Holman","feugiat.placerat@icloud.edu");
  
  INSERT INTO professors(professors_first_name,professors_last_name,professors_email)
  VALUES
  ("Richard","Johnson","eu@icloud.ca"),
  ("Kennedy","Gallegos","sed.tortor@icloud.couk"),
  ("Lucius","Wilkins","natoque@outlook.com"),
  ("Plato","Molina","tristique.senectus@protonmail.ca"),
  ("Drake","Fisher","netus@aol.org"),
  ("Rudyard","Justice","inceptos.hymenaeos@aol.net"),
  ("Magee","Stanley","magnis.dis@protonmail.edu"),
  ("Carson","Blair","id.enim@hotmail.couk"),
  ("Dolan","Mckinney","phasellus.fermentum@aol.edu"),
  ("Jacob","Chavez","ornare@icloud.org");
  
  INSERT INTO courses(courses_name,courses_description,courses_professors_id)
  VALUES
  ("Historia","ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo",7),
  ("Historia del arte","Quisque ornare tortor at risus. Nunc ac sem ut dolor",7),
  ("Biología Marina","lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc",2),
  ("Algebra","risus quis diam luctus lobortis. Class aptent taciti sociosqu ad",5),
  ("Mecánica Aplicada","lacus vestibulum lorem, sit amet ultricies sem magna nec quam.",9),
  ("Tecnología Química","Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi",8),
  ("Historia Contemporánea","magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl.",10),
  ("Automática y Control","Curabitur egestas nunc sed libero. Proin sed turpis nec mauris",4),
  ("Química Aplicada","vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci",6),
  ("Mecánica de Fluidos","Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non,",9),
  ("Métodos numéricos","tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh",4),
  ("Termodinámica","commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit,",1),
  ("Electrónica General","Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede,",3),
  ("Ecuaciones Diferenciales","dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec,",5);
  
  INSERT INTO grades(grades_students_id,grades_courses_id,grades_grade)
  VALUES
  (19,3,7),
  (23,11,3),
  (15,12,3),
  (27,1,5),
  (42,7,7),
  (2,13,9),
  (36,4,5),
  (31,3,2),
  (11,12,5),
  (14,10,6),
  (33,8,6),
  (39,13,3),
  (30,10,4),
  (17,3,0),
  (16,9,4),
  (10,10,10),
  (23,12,5),
  (41,5,1),
  (40,4,6),
  (26,5,10),
  (35,6,3),
  (33,6,6),
  (2,11,10),
  (24,12,10),
  (18,9,2),
  (36,3,0),
  (28,12,1),
  (9,2,6),
  (34,12,4),
  (39,12,9),
  (9,13,6),
  (17,6,5),
  (16,2,6),
  (30,7,9),
  (43,5,3),
  (23,7,9),
  (24,6,9),
  (18,11,8),
  (22,11,0),
  (5,13,2),
  (14,13,3),
  (6,8,3),
  (6,2,2),
  (10,3,7),
  (39,5,9),
  (2,14,7),
  (44,10,7),
  (41,12,7),
  (23,14,8),
  (44,11,4),
  (29,13,6),
  (22,7,4),
  (40,14,3),
  (32,12,5),
  (26,10,6),
  (7,9,10),
  (30,14,3),
  (20,6,9),
  (32,5,0),
  (36,5,0),
  (16,4,4),
  (45,12,4),
  (32,7,7),
  (18,3,4),
  (8,3,6),
  (29,14,1),
  (39,7,1),
  (31,8,7),
  (42,4,3),
  (2,7,9),
  (14,12,5),
  (25,6,8),
  (9,11,6),
  (39,6,6),
  (11,14,8),
  (42,6,7),
  (21,4,4),
  (2,8,2),
  (32,2,4),
  (16,5,8),
  (18,12,1),
  (25,4,4),
  (33,11,9),
  (3,8,5),
  (22,11,2),
  (2,3,4),
  (19,8,5),
  (15,7,3),
  (13,8,10),
  (32,3,8),
  (28,7,9),
  (16,7,7),
  (42,10,8),
  (3,2,7),
  (40,13,8),
  (13,11,4),
  (17,10,7),
  (39,7,6),
  (8,6,5),
  (43,11,3);
  